### ISSUE TITLE
Some enhancements

### ISSUE THREAD

**Issue by faergeek** [cecton/aur-retroarch-rbp-git#3]
Hi! Thanks for packaging retroarch for raspberry pi 👍 .

I just wanted to make pull requests for these things:

1. Add `.gitignore`.
2. Add patch for default config (`/etc/retroarch.cfg`) which points to paths for other packages like in upstream arch package.
3. Completely remove SDL or other things which don't work or work poorly. May be just to speed up building and remove things that don't work anyway. For that I'm going to use http://www.lakka.tv/ as a reference.
4. Optimize binary as far as it's possible :-) Or just as far as I can.
5. Try to figure out how to make `dispmanx` actually work as it doesn't currently work for me :-(

Does it make sense to submit them? May be only some of them?

Also I would like to know which raspberry pi version you're targeting as I only have raspberry pi 2. Is there any way to test on other versions?

Thanks a lot 👍

**Comment by cecton** [comment]
Sorry apparently I missed that ticket (I don't know why but I'm not receiving all the emails from github apparently).

1. hmm sure if you think it's any useful, I'm not used to receive contributions on this repo. I did added an automatic build for the PR on Travis CI. It builds only for rpi1 and 2 unfortunately not 3.
2. Sure, I have no idea why the settings would be wrong by default. I'm using the default settings and it doesn't seem to break on my rpi2. Can you show man an example?
3. I removed already SDL2 and mesa and mesa-libgl which are not needed apparently. It will still build those if they are installed but I guess this behavior is better.
4. Great! I have to idea how to do that
5. Try on a clean installation. I should do the same...
6. I'm sorry again for the delay...

Sure! Submit all the things :shipit: 

I'm testing natively on rpi2 but you can find the builds on Travis CI: https://travis-ci.org/cecton/aur-retroarch-rbp-git
